myportfolio/myportfolio/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

myportfolio/portfolio/urls.py
from django.urls import path
from . import views

app_name = 'portfolio'
urlpatterns = [
    path('',views.HomeTemplateView.as_view(),),
    path('user_info/', views.user_info, name='user_info'),
]

myportfolio/portfolio/models.py
from django.db import models


# Create your models here.
class About(models.Model):
    short_description = models.TextField()
    description = models.TextField()
    image = models.ImageField(upload_to = "about")

    class Meta:
        verbose_name = "About me"
        verbose_name_plural = "About me"

    def __str__(self):
        return "About me"

# Service Model
class Service(models.Model):
    name = models.CharField(max_length=100, verbose_name="Service name")
    description = models.TextField(verbose_name="About service")

    def __str__(self):
        return self.name

#Recent work Model
class RecentWork(models.Model):
    title = models.CharField(max_length=100, verbose_name="Work title")
    image = models.ImageField(upload_to="works")

    def __str__(self):
        return self.title

#Client Model
class Client(models.Model):
    name = models.CharField(max_length=100, verbose_name="Client Name")
    description = models.TextField(verbose_name="Client Say")
    image = models.ImageField(upload_to="clients",default="default.png")

    def __str__(self):
        return self.name

class User(models.Model):
    full_name = models.CharField(max_length=128)
    email = models.EmailField(max_length=264,unique=True)
    messages = models.TextField(verbose_name="message")

    def __str__(self):
        return self.full_name

myportfolio/portfolio/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from .models import *

# Create your views here.
class HomeTemplateView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['about'] = About.objects.first()
        context['services'] = Service.objects.all()
        context['works'] = RecentWork.objects.all()

        return context

def user_info(request):
        if request.method == 'POST':
            if request.POST.get('full_name') and request.POST.get('email') and request.POST.get('messages'):
                user=User()
                user.full_name = request.POST.get('full_name')
                user.email = request.POST.get('email')
                user.messages = request.POST.get('messages')
                user.save()


                return render(request, 'home.html')

        else:
                return render(request,'home.html')

myportfolio/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Personal Portfolio</title>
    {% include 'includes/stylesheets.html' %}
</head>
<body>

<div class="loader_bg">
    <div class="loader"></div>
</div>

<nav class="navbar navbar-custom navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                <i class="fa fa-bars"></i>
            </button>
            <a class="navbar-brand page-scroll" href="/">Akash Mishra</a>
        </div>
        <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a class="smooth-menu" href="#home">Home</a></li>
                <li><a class="smooth-menu" href="#about">About</a></li>
                <li><a class="smooth-menu" href="#services">Technology</a></li>
                <li><a class="smooth-menu" href="#portfolio">Portfolio</a></li>
                <li><a class="smooth-menu" href="#testimonial">Testimonial</a></li>
                <li><a class="smooth-menu" href="#contact">Contact</a></li>
            </ul>
        </div>
    </div>
</nav>

{% block content %}{% endblock %}

<div class="footer-area">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-center">
                <p align='left'>&copy;Copyright 2019</p>
            </div>
        </div>
    </div>
</div>
{% include 'includes/scripts.html' %}
</body>
</html>

myportfolio/templates/home.html
{% extends 'base.html' %}

{% block content %}

    <div id="home" class="banner-area section-padding">
        <div class="bg-overlay black"></div>
        <div class="containter">
            <div class="row">
                <div class="col-md-12">
                    <div class="welcome-text">
                        <div class="name-area wow fadeInDown" data-wow-delay="0.4s">I am Python developer with having 8.4 year of experience</div>
                        <h2 class="wow fadeInDown" data-wow-delay="0.8s">8+Year of Experience | Leveraging Python for Innovative Solutions | Python, Django, and Flask Expertise | AWS (EC2, EKS, Lambda) | Mentor at FFE</h2>
                        <h3 class="wow fadeInDown" data-wow-delay="1.2s">Flexible, Keen to Learn new Technology, Self Motivated Person</h3>
                        <a href="#about" class="my-btn-1 wow fadeInDown" data-wow-delay="1.6s">Learn more</a>
                        <a href="#contact" class="my-btn-2 wow fadeInDown" data-wow-delay="1.6s">Get in touch</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {#    About section#}

    <div id="about" class="about-area section-padding">
        <div class="container">
            <div class="row">
                <div class="col-md-7 col-sn-8 col-xs-12 wow fadeInLeft" data-wow-delay="0.2s">
                    <div class="about-left">
                        <h2 class="section-title">About Me</h2>
                        <div class="line"></div>
                        <h4>{{ about.short_description }}</h4>
                        <p>{{ about.description }}</p>
                        <a href="media/about/Akash_Mishra - Python_Developer.docx" download>Download CV&nbsp;<i class="fa fa-download"></i></a>
                    </div>
                </div>
                <div class="col-md-5 visible-md visible-lg wow fadeInDown" data-wow-delay="0.6s">
                    <div class="profile">
                        <img src="{{ about.image.url }}" alt="Profile image" class="img-responsive">
                    </div>
                </div>
            </div>
        </div>
    </div>

    {#    Services Section#}
    <div id="services" class="section-padding">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="section-header text-center">
                        <h2>Technology I Know</h2>
                    </div>
                </div>
            </div>
            <div class="row">
                {% for service in services %}

                    <div class="col-md-4 col-sm-4">
                        <div class="single-service wow fadeInDown" data-wow-delay="0.2s">
                            <i class="icon icon-wallet"></i>
                            <h2>{{ service.name }}</h2>
                            <p>{{ service.description }}</p>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

    {#    Recent Works Section#}
    <div id="portfolio" class="portfolio-area section-padding">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="section-header">
                        <h2>My Recent Works</h2>
                    </div>
                </div>
            </div>
            <div class="row">
                {% for work in works %}
                    <div class="col-md-4 col-sm-4 col-xs-12 no-padding">
                        <div class="gallery-items">
                            <a class="view img" href="{{ work.image.url }}">
                                <img src="{{ work.image.url }}" alt="work image">
                            </a>

                            <div class="gallery-text">
                                <h2>{{ work.title }}</h2>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

    {#    Contact section#}

    <div class="invitation-area section-padding">
        <div class="container">
            <div class="row">
                <div class="single-invite text-center">
                    <h2>Do you have any opening, and want me to hire </h2>
                    <p>Please feel free to reach out to me &#128578</p>
                    <p>Official Notice Period: 90 days</p>
                    <p><b>Email :</b> akashmishra454@gmail.com </p>
                    <p><b> Contact number : </b> +91-9511911944/ +91-9450359964 </p>
                    <a href="#contact" class="my-btn-3">Get started</a>
                </div>
            </div>
        </div>
    </div>

    <div id="contact" class="contact-area section-padding">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="section-header text-center">
                        <h2>Contact Me</h2>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-8 col-md-offset-2 col-lg-8 col-lg-offset-2 box-contact-form">

                  <!--  <form id="contact-form" method="POST" action=""> -->
                    <form method="POST" role="form" action="{% url 'portfolio:user_info' %}" enctype="multipart/form-data">
                      {% csrf_token %}
                        <div class="message"></div>

                        <div class="controls">

                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group wow fadeInDown" data-wow-delay="0.2s">
                                        <input id="form_name" type="text" name="full_name" class="form-control"
                                               onkeyup="success_name()"
                                               placeholder="Enter your full name *" required="required"
                                               data-error="Fullname is required." disabled>
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group wow fadeInDown" data-wow-delay="0.4s">
                                        <input id="form_email" type="email" name="email" class="form-control"
                                               onkeyup="success_mail()"
                                               placeholder="Enter your email *" required="required"
                                               data-error="Valid email is required." disabled>
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group wow fadeInUp" data-wow-delay="0.6s">
                                        <textarea id="form_message" name="messages" class="form-control"
                                                  onkeyup="success_text()"
                                                  placeholder="APOLOGIES!! Intentionally disabled these fields as gmail less Secure app is not working after 30 May 2022. working on this. PLEASE EMAIL ME at my Gmail id AKASHMISHRA454@GMAIL.COM" rows="4" required="required"
                                                  data-error="Leave a message for me" disabled></textarea>
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                                <div class="col-md-12">
                          <!--          <input class="btn btn-send" type="submit" value="Post"/>   -->
                                    <button class="btn btn-send" id="button" value="Post" onclick=alertFucntion() disabled>Send message</button>
                                    <script>
                                    function alertFucntion() {
                                    alert("Email has been sent Successfully!");
                                    }
                                    function success_text() {
                                     if(
                                     document.getElementById("form_message").value==="") {
                                     document.getElementById('button').disabled = true;
                                     } else {
                                     document.getElementById('button').disabled = false;
                                     }}
                                     function success_mail() {
                                     if(
                                     document.getElementById("form_email").value==="") {
                                     document.getElementById('button').disabled = true;
                                     } else {
                                     document.getElementById('button').disabled = false;
                                     }}
                                     function success_mail() {
                                     if(
                                     document.getElementById("form_name").value==="") {
                                     document.getElementById('button').disabled = true;
                                     } else {
                                     document.getElementById('button').disabled = false;
                                     }}
                                    </script>
                                </div>
                            </div>
                        </div>

                    </form>

                </div>

            </div>
        </div>
    </div>

{% endblock %}

myportfolio/templates/includes/scripts.html
{% load static %}

<!--Latest version JQuery-->
<script src="{% static 'js/jquery.min.js' %}"></script>

<!--Bootstrap js-->
<script src="{% static 'js/bootstrap.min.js' %}"></script>

<!--easing js-->
<script src="{% static 'js/jquery.easing.min.js' %}"></script>

<!--mixitup js-->
<script src="{% static 'js/jquery.magnific-popup.js' %}"></script>

<!--Owl Carousel js-->
<script src="{% static 'js/owl.carousel.js' %}"></script>

<!--Validator js-->
<script src="{% static 'js/validator.js' %}"></script>

<!--Contact js-->
<script src="{% static 'js/contact.js' %}"></script>


<!--Bootstrap js-->
<script src="{% static 'js/wow.min.js' %}"></script>

<!--Theme js-->
<script src="{% static 'js/main.js' %}"></script>

myportfolio/templates/includes/stylesheets.html
{% load static %}

<!--Theme Fonts-->
<link href="https://fonts.googleapis.com/css?family=Poppins:400,400i,600,700,800" rel="stylesheet">

<!--Bootstrap css-->
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

<!--Font Awesome css-->
<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">

<!--Font Awesome css-->
<link rel="stylesheet" href="{% static 'css/animate.css' %}">

<!--Owl carousel css-->
<link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
<link rel="stylesheet" href="{% static 'css/owl.theme.default.css' %}">

<!--Magnific popup css-->
<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">

<!--icon css-->
<link rel="stylesheet" href="{% static 'css/line-icons.min.css' %}">

<!--Template css-->
<link rel="stylesheet" href="{% static 'css/style.css' %}">

<!--Template css-->
<link rel="stylesheet" href="{% static 'css/responsive.css' %}">